---
title: "Computing for the Social Sciences"
format:
  html:
    toc: false
    theme: cosmo
---

### Course Information Fall 2025

<div class="my-4"></div>

**Lectures**: Mondays & Wednesdays, 1:30–3:20 PM, 1155 Building E. 60th St, Room 295 

<div class="my-4"></div>

**Teaching Team**:  

- Instructor: Sabrina Nardin (she/her) – [nardin@uchicago.edu](mailto:nardin@uchicago.edu)  
- TA: Zach Meyer (he/him) – [zmeyer@uchicago.edu](mailto:zmeyer@uchicago.edu)
- TA: Zixuan Zhou (she/her) – [zixuanzhou@uchicago.edu](mailto:zixuanzhou@uchicago.edu)

<div class="my-4"></div>

**Office Hours (all in-person)**:

| Day & Time                     | Type                                                                 | Location              | Person |
|--------------------------------|----------------------------------------------------------------------|-----------------------|------------|
| Mon 3:20–3:30 PM (after class) | *Drop-in (short questions)*                                          | Same as classroom     | Sabrina    |
| Tue 2:00–4:00 PM               | [*By appointment*](https://calendar.app.google/xtDH9Pnf8yJtP9jg6)    | 1155 Bldg, Room 221A  | Sabrina    |
| Wed 11:00 AM–12:40 PM          | [*By appointment*](https://calendar.app.google/sXeZq7QVB349yMiJ7)    | 1155 Bldg, Room 222   | Zach       |
| Wed 12:40–1:10 PM              | *Drop-in (short questions)*                                          | 1155 Bldg, Room 222   | Zach       |
| Wed 3:20–3:30 PM (after class) | *Drop-in (short questions)*                                          | Same as classroom     | Sabrina    |
| Thu 1:30–3:10 PM               | [*By appointment*](https://calendar.app.google/Gt8Bci5Ciw7n1uEA8)    | 1155 Bldg, Room 222   | Zixuan     |
| Thu 3:10–3:40 PM               | *Drop-in (short questions)*                                          | 1155 Bldg, Room 222   | Zixuan     |

<div class="my-4"></div>

**Quick Links**:  

- [R Workbench](https://macss-r.uchicago.edu/)  
- [Canvas](https://canvas.uchicago.edu/courses/66343)  
- [Ed Discussion](https://edstem.org/us/courses/86758/discussion)
- [UChicago GenAI](https://genai.uchicago.edu/en)


