---
title: "Lecture 2: Git & GitHub with RStudio"
date: 2026-06-16
summary: "Intro to Git & GitHub with RStudio"
url_slides: 02-slides.qmd
#url_code: css-materials/git
format: html
page-layout: full
draft: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Info and Materials

* **Date**: {{< meta date >}}
* **Topics**: {{< meta summary >}}
* **Slides**: To be posted before class
* **Code**: No in-class code for this session

<!-- 
* **Slides**: [View Slides]({{< meta url_slides >}})
-->


## Learning Objectives

- Understand what Git is and why it's useful
- Create a Git repository in RStudio
- Connect your Git repository to GitHub
- Practice staging, committing, and pushing changes


## Before Class

- Complete the Lecture 1 "Before Class" activities, if you haven't already. *You must have a GitHub account to be able to follow along today. Plan ahead: GitHub requires two-factor authentication (you can use an authentication app of your choice, or the university Duo system, but setup may require some time)*  
- Review Lecture 1 materials.
- Finish the R Markdown tutorial we started in Lecture 1 and complete the exercises. No submission is needed.
- If you have not already done so, complete Lecture 1 participation questions. You can find them in the Lecture 1 Zoom chat (the recording is available on Canvas) or in [this document](https://docs.google.com/document/d/1f5jZ1ynOMV-axF-toNtec-KyOwhLvSYZCx0BlPaslxQ/edit?usp=sharing) after class. They will remain open until the start of Lecture 2.


## Readings

- Chapter 1 of [Happy Git and GitHub for the useR](https://happygitwithr.com/big-picture)
- Read the [Software Setup](../setup/index.qmd) page of this website. No need to do it: we'll go through this together in class today!
