---
title: "Lecture 4: Graphs for Data Analysis with ggplot2"
date: 2026-06-18
summary: "Graphs for Data Analysis"
url_slides: 04-slides.qmd
url_code: css-materials/eda
page-layout: full
draft: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Info and Materials

* **Date**: {{< meta date >}}
* **Topics**: {{< meta summary >}}
* **Slides**: To be posted before class
* **Code**: To be posted before class

<!--
* **Slides**: [View Slides]({{< meta url_slides >}})
* **Code**: `usethis::use_course("{{< meta url_code >}}")`
-->

## Learning Objectives

- Practice using `ggplot2` to explore (see Ch.10 below) and communicate data (see Ch.11 below) with graphs
- Identify best graph types (e.g., bar chart vs. histogram) based on variable types (e.g., categorical vs. numeric)
- Interpret what a graph shows about the data


## Before Class

- Make sure your setup works as expected (see Lecture 1 and 2). If not, reach out for help
- Review Lecture 3 materials to familiarize with `ggplot2`
- If you have not already done so, complete Lecture 3 participation questions. You can find them in the Lecture 3 Zoom chat (the recording is available on Canvas > UChicago Main Zoom > Cloud Recordings) or in [this document](https://docs.google.com/document/d/1f5jZ1ynOMV-axF-toNtec-KyOwhLvSYZCx0BlPaslxQ/edit?usp=sharing) after class. They will remain open until the start of this lecture (e.g., Lecture 4).
- HW1 is open and due next Monday (remember no late submissions allowed). Access it from the [Assignments page](https://brinasab.github.io/css-website-summer/hw/). 


## Readings

- ["Chapter 10 Exploratory Data Analysis"](https://r4ds.hadley.nz/EDA.html) from "R for Data Science" 2nd Edition
- ["Chapter 11 Communication"](https://r4ds.hadley.nz/communication.html) from "R for Data Science" 2nd Edition

For additional resources on `ggplot2` readings, see Lecture 3

<!--
  * Cheat sheets and documentation for `ggplot2` and `dplyr` (from previous lectures)
  * [ggplot2 Cheat Sheet](https://raw.githubusercontent.com/rstudio/cheatsheets/main/data-visualization.pdf)
  * [ggplot2 Official Documentation](https://ggplot2.tidyverse.org/index.html)
  * [dplyr Cheat Sheet](https://rstudio.github.io/cheatsheets/html/data-transformation.html)
  * [dplyr Official Documentation](https://dplyr.tidyverse.org/)
-->