---
title: "Lecture 5: Week 1 Review"
date: 2026-06-22
summary: "Week 1 Review and Q&A"
url_slides:
url_code:
page-layout: full
draft: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Info and Materials

* **Date**: {{< meta date >}}
* **Topics**: {{< meta summary >}}
* **Slides**: No slides for this session
* **Code**: No in-class code for this session

<!--
* **Slides**: [View Slides]({{< meta url_slides >}})
* **Code**: `usethis::use_course("{{< meta url_code >}}")`
-->

## Learning Objectives

Today, we will review key topics from Week 1 and answer questions about Quiz 1 and Homework Assignment 1. We will still have Poll Everywhere participation questions, plus time for more questions. Depending on how much we need to review, we may finish a bit early. Any remaining time will be used for individual office hours.


## Before Class

- Bring any questions you have about the Week 1 materials!
- If you have not already done so, complete Lecture 4 participation questions. You can find them in the Lecture 4 Zoom chat (the recording is available on Canvas > UChicago Main Zoom > Cloud Recordings) or in [this document](https://docs.google.com/document/d/1f5jZ1ynOMV-axF-toNtec-KyOwhLvSYZCx0BlPaslxQ/edit?usp=sharing) after class. They will remain open until the start of this lecture (e.g., Lecture 5). Make sure to enter your name as you answer (do not answer a "guest").
- HW1 is open and due today, Monday June 22 at 11:59 PM Chicago time, remember no late submissions allowed. Access it from the [Assignments page](https://brinasab.github.io/css-website-summer/hw/) and submit on Canvas. 
- Complete Quiz 1 from [Canvas](https://canvas.uchicago.edu/courses/72552). You have unlimited attempts; due 1h before today's class, no late submissions accepted.


