---
title: "Lecture 6: Intro to dplyr; Pipes"
date: 2026-06-23
summary: "Wrangling Data with dplyr; Using R Pipes"
url_slides: 06-slides.qmd
url_code: css-materials/dplyr-pipes
page-layout: full
draft: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Info and Materials

* **Date**: {{< meta date >}}
* **Topics**: {{< meta summary >}}
* **Slides**: [View Slides]({{< meta url_slides >}})
* **Code**: `usethis::use_course("{{< meta url_code >}}")`

<!--
* **Slides**: To be posted before class
* **Code**: To be posted before class
-->

## Learning Objectives

- Approach coding tasks as problem-solving by thinking through the steps before writing code
- Understand R logical operators
- Use the following dplyr functions: `select()`, `filter()`, `group_by()`, and `summarize()`
- Chain commands using the pipe `|>` and recognize mistakes to avoid



## Before Class

- If you have not already done so, complete Lecture 5 participation questions. You can find them in the Lecture 5 Zoom chat (the recording is available on Canvas > UChicago Main Zoom > Cloud Recordings) or in [this document](https://docs.google.com/document/d/1f5jZ1ynOMV-axF-toNtec-KyOwhLvSYZCx0BlPaslxQ/edit?usp=sharing) after class. They will remain open until the start of this lecture (e.g., Lecture 6). Make sure to enter your name as you answer, so we can properly record your participation (do not answer a "guest").
- Check the reading below and come with questions!



## Readings

* ["Chapter 3 Data transformation"](https://r4ds.hadley.nz/data-transform) from "R for Data Science" 2nd Edition 

Additional Resources:

* [dplyr Cheat Sheet](https://rstudio.github.io/cheatsheets/html/data-transformation.html)
* [dplyr Official Documentation](https://dplyr.tidyverse.org/)

