---
title: "Lecture 8: Missing Data; Factors"
date: 2026-06-25
summary: "Missing Data; Factors"
url_slides: 08-slides.qmd
url_code: css-materials/factors
page-layout: full
draft: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Info and Materials

* **Date**: {{< meta date >}}
* **Topics**: {{< meta summary >}}
* **Slides**: [View Slides]({{< meta url_slides >}})
* **Code**: `usethis::use_course("{{< meta url_code >}}")`

<!--
* **Slides**: To be posted before class
* **Code**: To be posted before class
-->

## Learning Objectives

- Detect, handle, and clean explicit missing data in R
- Understand factors in R and how to use them effectively


## Before Class

- If you have not already done so, complete Lecture 7 participation questions. You can find them in the Lecture 7 Zoom chat (the recording is available on Canvas > UChicago Main Zoom > Cloud Recordings) or in [this document](https://docs.google.com/document/d/1f5jZ1ynOMV-axF-toNtec-KyOwhLvSYZCx0BlPaslxQ/edit?usp=sharing) after class. They will remain open until the start of this lecture (e.g., Lecture 8). Make sure to enter your name as you answer, so we can properly record your participation (do not answer a "guest").
- Check the reading below and come with questions!
- Assignments coming up:
  - Quiz 2 will open right after this class, check [Canvas](https://canvas.uchicago.edu/courses/72552) and it's due Monday of Week 3 before class
  - Assignment 2 will open tomorrow (Friday 6/26) and it's due next Thursday; you will find it under [Assignments](../hw) of this website as "Homework 2"

## Readings

- Missing data: ["Chapter 18 Missing values"](https://r4ds.hadley.nz/missing-values.html) from "R for Data Science" 2nd Edition
- ["Chapter 16 Factors"](https://r4ds.hadley.nz/factors) from "R for Data Science" 2nd Edition
