---
title: "Computing for the Social Sciences: Lecture 8"
subtitle: "Topics: Missing Data; Factors"
author: "Sabrina Nardin, Summer 2026"
format:
  revealjs:
    theme: simple
    slide-number: true
    incremental: false
    css: ../style/styles.css
    code-overflow: wrap
    highlight-style: github
    ratio: 16:9
    chalkboard: true
    toc: false
    center: true
---

# Agenda {.center}

::: {.agenda-list}
1. Missing Data
2. Factors in R 
:::


<span style="font-size: 0.8em; color: #666;">
*Slides last updated on **`r format(Sys.Date(), '%B %d, %Y')`**. Slides authored by Sabrina Nardin. AI used to polish slides style and fix typos.*
</span>

```{r pkgs, include = FALSE, cache = FALSE}
library(tidyverse)
library(rcis)
library(knitr)
#library(here)
```


# 1. Missing Data {.slide .center .middle}

---

## What Are Missing Data?

R distinguishes two types of missing data:

- **Explicit missing data**: visible `NA` or `NaN` values in the dataset
- **Implicit missing data**: data that was never recorded

In this course, we focus on **explicit missing data**. For implicit missing data, see [R for Data Science Ch. 18](https://r4ds.hadley.nz/missing-values)

:::{.callout-note title="Definitions"}
Explicit = the missing value is recorded in the data, ideally as `NA` (Not Available)  
Implicit = value was never recorded in the data
:::

<!--
- `NA` = Not Available (general-purpose missing value)  
- `NaN` = Not a Number (typically from invalid math like `0/0` or `0 * Inf`)  
- Both behave similarly, but `NaN` specifically signals a **computational error**
See [Ch. 12.2.2](https://r4ds.hadley.nz/logicals#sec-na-comparison) for how `NA` behaves in comparisons.
:::
-->

---

## How Missing Data Behave

Any operation involving a missing value will return a missing value (see [Ch. 12.2.2 Missing values](https://r4ds.hadley.nz/logicals#sec-na-comparison) for more):

```r
NA > 5

sum(c(3, 1, 4, NA)
sum(c(3, 1, 4, NA), na.rm = TRUE)

mean(c(3,1,4,NA))
mean(c(3, 1, 4, NA), na.rm = TRUE)  
```

---

## Common Ways to Handle Missing Data

Working with (explicit) missing data is usually a **decision process*:** 

<!--
Before deciding what to do with missing data, we first need to find it. Then we can choose whether to ignore it in calculations or remove it from the dataset.
-->

A. `is.na()` to find missing values   
B. `na.rm = TRUE` to ignore missing values in calculations  
C. `drop_na()` to remove missing values; use carefully 


---

## A. Find Missing Data with is.na()

**The most common way to check for missing values in R is with `is.na()`**, which returns `TRUE` when a value is missing, and `FALSE` when a value is present.

For example, this code uses `is.na()` to check for missing values in one variable from `penguins_raw`:

```r
# load libries and data
library(tidyverse)
library(palmerpenguins)
data(penguins_raw)

# check for missing using base R syntax
is.na(penguins_raw$Sex)
sum(is.na(penguins_raw$Sex))
table(is.na(penguins_raw$Sex))

# check for missing data using tidyverse syntax
penguins_raw |> summarize(sum(is.na(Sex)))
penguins_raw |> count(is.na(Sex)) 
penguins_raw |> summarize(across(everything(), ~ sum(is.na(.)))) |> print(width = Inf)
```

<!-- spend time on this code

POINT 1: you can also name the resulting output

POINT 2:`is.na(penguins_raw, Sex)` won't work
`is.na()` is a base R function, not a dplyr verb. It checks the object you give it.
So this works: `is.na(penguins_raw$Sex)` works bcs R interprets it as an object because `penguins_raw$Sex` directly selects one column
This does not work: `is.na(penguins_raw, Sex)` because `is.na()` does not have a second argument for choosing a column.
That's why in tidyverse code, we usually use `is.na()` inside a dplyr verb

POINT 3
penguins_raw |>
     summarize(across(everything(), function(x) sum(is.na(x))) |>
     print(width = Inf)
-->

---

## A. Find Missing Data with is.na()

To pull out and check the rows where a value is missing: use `is.na()` inside `filter()` to keep rows where a value *is missing* or *is not missing*, as follows:

```r
# keep rows where sex is missing
filter(penguins_raw, is.na(Sex)) |> View()   # correct  
filter(penguins_raw, Sex == NA)  |> View()   # incorrect

# keep rows where sex is NOT missing
filter(penguins_raw, !is.na(sex))
```

Remember: we cannot use `== NA` to check for missing values (`NA` means “unknown,” so R cannot evaluate it). Use `is.na()` instead.

<!--
``==` compares two known values, but `NA` means the value is unknown or missing.  
Because R does not know what the missing value is, it cannot say whether another value is equal to it.
-->

---

## B. Ignore Missing Data with na.rm = TRUE 

**Use `na.rm = TRUE` to exclude missing values when performing calculations.** Often used together with `summarize()` when calculating things like mean, sum, standard deviation:

```r
penguins_raw |> summarize(avg_mass = mean(`Body Mass (g)`, na.rm = TRUE))
penguins_raw |> summarize(sum_mass = sum(`Body Mass (g)`, na.rm = TRUE))
```

<!-- show the difference with and without the na.rm = TRUE and try change it to FALSE -->

<br>

:::{.callout-tip}
The command `na.rm = TRUE` does not remove missing data from the variable(s), It only tells R to **skip missing values for that specific calculation**.
:::
 
</br>

---

## C. Remove Missing Data with drop_na()

**Use `drop_na()` to remove rows with missing values.** Either across all columns or in specific columns (safer/most common):

```r
penguins_raw |>
  drop_na(`Body Mass (g)`) |>
  summarize(avg_mass = mean(`Body Mass (g)`))
```
<!-- 
drop_na()  
drop_na(`Body Mass (g)`, Sex) 
-->

<br>

:::{.callout-warning}
Be careful: `drop_na()` actually removes rows from the data you are working with.
It removes the entire row, not just the missing cell. This can accidentally remove useful data from other variables in the same row. Before using it, check (see previous slides).
:::

</br>

---

## 💻 Practice: Handling Missing Data

0. **Rename:** use the `penguins_raw` dataset and rename `Flipper Length (mm)` to `flipper_length_mm`. Save the result as a new dataframe (call it `penguins_clean` or `p`)

Use the new dataframe with the renamed variable for the tasks below (copy/adapt code from these slides):

1. **Detect missing values:** use `is.na()` and `sum()` to count how many are missing in the variable flipper length

2. **Exclude missing from calculations:** use `na.rm = TRUE` inside `mean()` to calculate the average flipper length

3. **Drop missing values:** use `drop_na()` to remove rows with missing values in flipper length

Once done, [share your code here](https://codeshare.io/29X3QM){target="_blank"}.


<!--
# 0. Rename
p <- penguins_raw |> rename(flipper_length_mm = `Flipper Length (mm)`)

# 1. Detect missing values
p |> summarize(n_missing = sum(is.na(flipper_length_mm)))

# 2. Exclude missing values from calculation
p |> summarize(avg_flipper = mean(flipper_length_mm, na.rm = TRUE))

# 3. Drop missing values and calculate again
p |> drop_na(flipper_length_mm)
-->

---

## Ways to Fill or Replace Missing Data

Main functions to replace or fill missing values:

- `replace_na()` – replace missing values with a specified value  
- `fill()` – carry values forward or backward (from the package `tidyr`)  
- `coalesce()` – return the first non-missing value across multiple columns

See [Chapter 18](https://r4ds.hadley.nz/missing-values) of *R for Data Science* for more.

<!-- NOTE: REMOVE THIS PART FOR CSP, KEEP FOR CSS 
ALSO EXPAND THE EXAMPLE ON HOW TO REPLACE OR REFILL MISSING DATA

## Factors and Empty Groups

Example from [Chapter 18](https://r4ds.hadley.nz/missing-values) of *R for Data Science*.

Create a dataset with with one variable defined as factor with two levels (yes and no):

```r
health <- tibble(
  name   = c("Ikaia", "Oletta", "Leriah", "Dashay", "Tresaun"),
  smoker = factor(c("no", "no", "no", "no", "no"), levels = c("yes", "no")),
  age    = c(34, 88, 75, 47, 56)
)
health
```

---

## Counting with Dropped vs. Retained Factor Levels

Without `.drop = FALSE`, unobserved factor levels are excluded:

```r
health |> count(smoker)
```

With `.drop = FALSE`, all factor levels are preserved (keeps all groups, even those not observed in the data since here they are all non-smokers)

```r
health |> count(smoker, .drop = FALSE)
```

---

## This Matters for Plotting

Compare these two codes.

The default behavior excludes empty levels from the plot:
```r
ggplot(health, aes(x = smoker)) +
  geom_bar() +
  scale_x_discrete()
```

Force display of all factor levels, including empty ones:
```r
ggplot(health, aes(x = smoker)) +
  geom_bar() +
  scale_x_discrete(drop = FALSE)
```
-->


# 2. Factors in R {.slide .center .middle}


## What are Factors in R?

At the most basic level **a factor is a specific data structure in R**.

But to fully understand factors, we first need to think about **variables with categories**: variables whose values come from a limited set of labels.

For example, the variable `species` in the `penguins` data has three possible labels or categories: `"Adelie"`, `"Chinstrap"`, and `"Gentoo"`.

---

## Real-world Examples of Variables with Categories

Some common examples of variables with categories are:

- Months of the year (January → December)
- Likert scales (Strongly Agree → Strongly Disagree)
- Educational attainment levels (High School → Graduate)
- Political parties
- Race/ethnicity categories
- Movies genre 
- Etc.

When we analyze data, we often want these categories to appear in a specific order. Sometimes that order is natural, such as months of the year. Other times, we define the order based on our analytic purpose. **Factors in R allow us to control such order!**

---

## How R Stores Variables with Categories

:::{.callout-note title="R Data Structures for Categorical Data"}

R has three main data structures to store variables with categories:

- **Character vector (default):** Data type for storing categorical data as plain strings (e.g., variable `months` with values "Jan", "Feb", "Mar", etc.). Values have no built-in order or grouping.

- **Numeric vector (occasionally):** Sometimes these are used to store categorical data as numbers (e.g., variable `months` with values 1, 2, 3), but lacks category labels or order.

- **Factor (preferred when order matters):** Data type for storing categorical data with defined levels. Values can be ordered according to the researcher needs. 

:::

---

## Why use Factors?

Let's define a character vector (e.g., the first of the three data structures mentioned in the previous slide) with four months and sort it. Run this code in R. What do you notice?   

```r
# Define
x1 <- c("Dec", "Apr", "Jan", "Mar")

# Check
x1
class(x1)

# Sort
sort(x1)
```

---

## Why use Factors?

From the output of the previous code we can see that **by default, R sorts character vectors alphabetically!**  

That works in some cases, but it is not ideal for months. Months have a meaningful chronological order: January, February, March, etc. and we want to preserve it.

**To tell R to use that order, we need to convert that character vector into a factor.**

---

## Why use Factors?

::: {.callout}
#### In the next slides, we learn two cases that you will likely encounter when working with factors:

1. Converting a **Character Vector to a Factor** (most common)
2. Converting a **Numeric Vector to a Factor** (sometimes needed when categories are stored as numbers)
:::

---

## 1. Converting a Character Vector to a Factor

Variables with categories are often stored in R as character vectors. By default, R sorts character vectors alphabetically. To use a different order, convert the character vector to a *factor* and define its *levels* in the order you want:

```r
# Character vector with month names
x1 <- c("Dec", "Apr", "Jan", "Mar")
class(x1)

# Define all set of possibile levels in desired order
month_levels <- c("Jan", "Feb", "Mar", "Apr", "May", "Jun", 
                  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")

# Convert to factor using those levels
y1 <- factor(x1, levels = month_levels)

# Check
y1
class(y1)
levels(y1)

# Compare sorting
sort(x1)  # Alphabetical
sort(y1)  # Chronological (by factor levels)
```

<!-- 
# SHORTER CODE

# Character vector with month names
x1 <- c("Dec", "Apr", "Jan", "Mar")
class(x1)

# Convert to factor using levels
y1 <- factor(x1, levels = c("Jan", "Mar", "Apr", "Dec"))

# if you pick another order, it will follow that one!
-->

---

## 2. Converting a Numeric Vector to a Factor

Sometimes variables with categories are stored in numeric vectors (as numbers, e.g., months as 1, 2, 12). To convert a numeric vector to a factor you need to specify *both levels and labels*:

```r
# Numeric vector with values representing months
x2 <- c(12, 4, 1, 3)
class(x2)

# Define all set of possibile numeric values we expect
month_levels <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)

# Define all labels we want to show for each value
month_labels <- c("Jan", "Feb", "Mar", "Apr", "May", "Jun", 
                  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec") 

# Convert to factor using levels and labels
y2 <- factor(x2, levels = month_levels,
                 labels = month_labels)

# Check
y2
class(y2)
levels(y2)

# Compare sorting
sort(x2)  # Numeric
sort(y2)  # Chronological (by factor levels)
```

<!-- 
**Question:** Why we are defining all possible levels and labels when only four are needed here? It will work either way, but it's good practice to define the full set and order of categories.

# SHORTER CODE

# Define all labels we want to show for each value
month_labels <- c("Jan", "Mar", "Apr", "Dec") 

# Convert to factor using levels and labels
y2 <- factor(x2, 
             levels = x2,
             labels = month_labels)
-->

---

## Levels and Labels in Factors

:::: {.columns}

::: {.column width="50%"}
### Levels  
- Define all possible factor categories
- Use to tell R the **order** of each category 
- Use **only levels** when your input data is already human readable, as in our first example (e.g., `"Jan"`, `"Feb"`, etc.)
:::

::: {.column width="50%"}
### Labels  
- Define optional names for each category
- Use to tell R **what to display** for each category  
- Use **labels and levels** when your input data uses codes, as in our second example (e.g., `1` to mean `"Jan"`), and you want to see more human readable labels. Labels are matched to levels.
:::

::::

---

## Levels and Labels in Factors

:::{.columns}

::: {.column width="50%"}
### When you input is a Character Vector

**Example values**: `"Jan"`, `"May"`, `"Oct"`

- Already human-readable
- (Often) only want to control the order  
- Convert to factor using only **`levels`** to order and label
- Example: `"May"` stays `"May"`
:::

::: {.column width="50%"}
### When you input is a Numeric Vector

**Example values**: `1`, `7`, `12`

- Not already human-readable
- Want to control the order & add readable labels
- Convert to factor using **`levels`** to order & **`labels`** to label
- Example: `1` becomes `"Jan"`,  `2` becomes `"Feb"`, etc.
:::

:::

<!--
## Summary of Levels and Labels in Factors


| **Type**           | **What It Represents**              | **Levels** — Store & Sort By                 | **Labels** — Display Names                    | **Example**                                              |
|--------------------|-------------------------------------|------------------------------------------------|------------------------------------------------|----------------------------------------------------------|
| Character Vector   | Categorical names (`"Jan"`)   | To control order (e.g., Jan, Feb, ..., Dec)   | Not needed — values are already readable       | `factor(x1, levels = month_names)`                      |
| Numeric Vector     | Coded categories (`1`)   | To match internal codes (e.g., 1 = Jan,..., 12 = Dec) | To assign readable labels to codes (e.g., "Jan", ...) | `factor(x2, levels = 1:12, labels = month_names)`       |

-->

---

## Levels and Labels in Factors: Examples

Before you run the code below in R, take a moment to guess the output of lines 5 and 12). What do you expect each code chunk to return, and why?

```r
# Example 1 with Input as Character Vector
a <- c("Low", "High", "Medium", "Low")
b <- factor(a, levels = c("Low", "Medium", "High"))
b
sort(b)

# Example 2 with Input as Numeric vector
i <- c(1, 3, 2, 1)
j <- factor(i, levels = c(1, 2, 3),
               labels = c("Low", "Medium", "High"))
j
sort(j)
```

<!--
# Note on Example 1

If you write labels rather then levels you get a wrong output!
And you can use both levels and labels also here but not needed
c <- factor(a, levels = c("Low", "Medium", "High"),
               labels = c("L", "M", "H"))
               
- Clear mapping: 1 → "Low", 2 → "Medium", 3 → "High"
- Labels are matched to levels, not to raw values
-->

---

## 💻 Practice 1: Character Vector → Factor

You are working with a **character vector**. Your goal is to convert it into a factor so, when you sort it, months follow their chronological order rather than alphabetical order.

The code below is not correct. Run it in R, identify the problem, and fix it:

```r
# Define a character vector representing months
m <- c("Dec", "Apr", "Jan", "Mar")
class(m)

# Attempt
mf <- factor(m, 
            levels = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
            labels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun",
                       "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"))
mf

# Compare sorting
sort(m)  
sort(mf)
```

---

## Solution 1: Character Vector → Factor

The input vector is made of characters ("Jan", "Feb"...) but the levels are given as numbers (1 to 12). R cannot match character values to numeric levels. The levels must match the actual values in the input vector.

```r
mf <- factor(m, 
             levels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun",
                        "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"))
mf
sort(mf)
```

---

## 💻 Practice 2: Numeric Vector → Factor

You are working with a **numeric vector** representing months as numbers. Your goal is the same: convert it into a factor, so when you sort it, months are in chronological order.

None of the attempts below is correct. Run each in R, explain why each does not work, and write one solution that works:

```r
# Define a numeric vector representing months
x <- c(12, 4, 1, 3, 1)
class(x)

   
# Attempt 1
y1 <- factor(x, levels = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12), 
                labels = c("Jan", "Mar", "Apr", "Dec"))
              
# Attempt 2
y2 <- factor(x, levels = c(1, 2, 3, 4),
                labels = c("Jan", "Mar", "Apr", "Dec"))
```
---

## Solution 2: Numeric Vector → Factor

- Attempt 1: mismatch between the number of labels and the levels. R throws an error.

- Attempt 2: R doesn't throw an error, but the code is incorrect because it forces levels 1 to 4, even though the input vector has values like 12. Since 12 isn’t among the defined levels, it becomes `NA`, leading to incorrect matches.

You can fix the code from the previous slide in the following ways:

```r
# Numeric vector representing months
x <- c(12, 4, 1, 3, 1)
class(x)

# Option 1 (reccomended)
month_labels <- c("Jan", "Feb", "Mar", "Apr", "May", "June", "July", "Aug", "Sept", "Oct", "Nov", "Dec")
month_levels = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)
y1 <- factor(x, levels = month_levels,  
                labels = month_labels)
class(y1)

# Option 2 (works but not reccomended, why?)
y2 <- factor(x, levels = c(1, 3, 4, 12),
                labels = c("Jan", "Mar", "Apr", "Dec"))

```

<!--

Option 1: creates a factor with all 12 months as possible levels, even if only 4 are used. Best option because it preserves the full structure of the variable.

Option 2: only keeps levels that appear in the data. Correct but incomplete, fails if new values (e.g. 5) appear later.

If you don’t specify `levels`, R will use the unique values in the data — so mismatches can lead to warnings or incorrect labeling. 

Tip: to avoid problems, specify both `levels` and `labels` explicitly.
-->

---

## Apply these concepts to a dataframe: scorecard

In most of your work, you deal with dataframes. We worked with the `scorecard` data to practice `ggplot2`. Now we use the same data to learn how we can use factors in a dataframe. 

Load libraries and explore data:
```r
library(tidyverse)
library(rcis)
data(scorecard)

glimpse(scorecard)
```
---

## Example: Plot the total number of schools in the U.S. by school type

This is the same question we did in class.
 
Since `type` is a categorical variable, we use a bar chart, which takes each category `"Public"`, `"Private nonprofit"`, `"Private for profit"` and automatically applies a frequency count to aggregate the data.

```r
ggplot(scorecard, mapping = aes(x = type)) +
  geom_bar() 
```

<br>

#### Our goal: reorder the bars!

</br>

---

## Method 1: Reorder bars manually with *factor()*

This is the method we used in the previous slide. It  more technical, but it gives you full control because you manually define the order of the factor levels.

```r
s <- scorecard |>
  mutate(type = factor(type,
                       levels = c("Private, nonprofit", "Public", "Private, for-profit")))

ggplot(s, aes(x = type)) +
  geom_bar()

```

Remember:

- check the column type (character or numeric) before transforming to factor using `factor()` as shown in the previous examples
- use it inside `mutate()` since you are working on column of a dataframe (and not a standalone vector like in the previous examples) 

---

## Method 2: Reorder the bars using tidyverse *fct_relevel()*

[`fct_relevel()`](https://forcats.tidyverse.org/reference/fct_relevel.html): allows to reorder factor levels by hand; this function behave similarly to `factor()`

```r
scorecard |> 
  mutate(type = fct_relevel(type, 
                           "Private, nonprofit", "Public", "Private, for-profit")) |>
ggplot(mapping = aes(x = type)) +
  geom_bar()

```

Note: you can write code also by "piping" the results of the `dplyr` code into `ggplot2` code, as illustrated here. 

---

## Method 3: Reorder the bars using tidyverse *fct_infreq()*

[`fct_infreq()`](https://forcats.tidyverse.org/reference/fct_inorder.html) sorts bars automatically by how common each category is (most to least frequent)

```r
scorecard |>
  mutate(type = fct_infreq(type)) |>
ggplot(aes(x = type)) +
  geom_bar()
```

---

## The "forcats" Package

:::{.callout-note title="Using factor() or a function from forcats?"}

The example from Method 1 uses `factor()`, the base R function for creating and managing factors. It is worth understanding because it shows the basic logic: a factor stores category labels together with an order of levels.

But because factors are so common in data analysis, the tidyverse includes a package called `forcats`, which provides simpler and more flexible tools for working with factors. Methods 2 and 3 from the previous slides use two `forcats` functions.

You are welcome to use the `forcats` tools, but learning `factor()` first helps you understand what’s happening behind the scenes.
:::

---

## The "forcats" Package

| Function         | What it does                                      | When to use                                      |
|------------------|---------------------------------------------------|--------------------------------------------------|
| `fct_relevel()`  | Manually sets the order of levels                 | When you need full manual control (similar to `factor(..., levels = ...)` in base R) |
| `fct_infreq()`   | Reorders factor levels by frequency (most to least common) | When you want categories ordered by how often they appear |
| `fct_reorder()`  | Reorders levels based on another variable (e.g., a numeric value) | Ideal for ordering bars by a summary statistic in `ggplot2` |


For more functions, see the [forcats documentation](https://forcats.tidyverse.org/)


--- 

## 💻 Challenge Exercise: Plot Tips by Weekday

In this exercise, you learn two things:

- to correctly use `stat = identity` with bar plots in `ggplot2`

- to control the order of categories in bar plots, using both `factor()` and the `forcats` function called `fct_relevel()`

---

## Create the Data

Copy and run the code below to create this dataset:

```r
library(tidyverse)

df <- tibble(
  week = c("Mon", "Wed", "Fri", "Wed", "Thu", "Sat", "Sat"),
  tip = c(10, 12, 20, 8, 25, 25, 30)
)

df
```

**Our Goal:** Create a bar plot with days of the `week` on the x-axis and the total `tip` amount on the y-axis (e.g., Saturday should display a bar with a height of $55, etc.).

---

## What's Wrong With This Plot?

Try this code. What does the height of each bar represent?

```r
ggplot(df, aes(x = week)) +
  geom_bar()
```

<fragment>

:::{.callout-note title="Why the bars do not show the actual tip amounts?"}
Why aren't the bars showing the actual tip amounts?  
- Because by default, `geom_bar()` uses `stat = "count"` to count how many rows fall into each category and puts those counts on the y-axis
- To plot the actual values (not counts), use `stat = "identity"` with both a x and y

:::


</fragment>

---

## Fix the y-axis on this bar plot

To fix this plot, we need to change the default `stat` from count to identity and manually specify both the `x` and `y` aesthetics. *See the [documentation](https://ggplot2.tidyverse.org/reference/geom_bar.html) or type `?geom_bar` in your R Console.*

```r
ggplot(df, aes(x = week, y = tip)) +
  geom_bar(stat = "identity") +
  labs(title = "Tips by Weekday", x = "Weekday", y = "Tip ($)")
```
This is much better, but we still do not have the bars nicely ordered....

---

## Fix the order of the bars using factor()

First, use base R's `factor()` to control the order of weekdays.

Replace the blank with the correct weekday order in the code below:

```r
df |>
  mutate(week = factor(week, levels = _____ )) |>
  ggplot(aes(x = week, y = tip)) +
  geom_bar(stat = "identity") +
  labs(title = "Tips by Weekday", x = "Weekday", y = "Tip ($)")
```

---

## Do the same but using fct_relevel()

Now, make the same plot using [`fct_relevel()`](https://forcats.tidyverse.org/reference/fct_relevel.html)

Replace the correct weekday order in the code below:

```r
df |>
  mutate(week = fct_relevel(week, ______ )) |>
  ggplot(aes(x = week, y = tip)) +
  geom_bar(stat = "identity") +
  labs(title = "Tips by Weekday", x = "Weekday", y = "Tip ($)")
```

<!--

Note: Leave out for CSP, bring back for CSS class. The actual code gives what I want (Sat is 55 etc) so unsure this is actually needed

## Group and Summarize

Now try grouping by weekday and summing the tips before plotting. Use either `factor()` or `fct_relevel()`.

```r
df |>
  mutate(week = factor(week, days)) |>   # factor() or fct_relevel()
  group_by(week) |>
  summarize(total_tip = sum(tip)) |>
  ggplot(aes(x = week, y = total_tip)) +
  geom_bar(stat = "identity") +
  labs(title = "Total Tips by Weekday", x = "Weekday", y = "Total Tip ($)")
```

Add this on slides: Keep these tricks in mind for the homework assignments, especially HW3 (e.g., how to change a variable into a factor and manually pass labels for your graphs; and how to reorder a variable chronologically (here Mon to Sat) for plotting purposes)

Consider putting this challenge in the practice exercises for today as well

For the dplyr part: add in the Rmd file demo an example of what happens if you calculate the mean of a boolean or logical vectors (T and F), say that T are interpreted as 1 and F are 0 for R; this is useful again for HW3!  
-->

---

## Solutions

```r
# With factor
days <- c("Mon", "Wed", "Thu", "Fri", "Sat")
df |>
  mutate(week = factor(week, levels = c("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"))) |>
  ggplot(aes(x = week, y = tip)) +
  geom_bar(stat = "identity") +
  labs(title = "Tips by Weekday", x = "Weekday", y = "Tip ($)")

# With fct_relevel
days <- c("Mon", "Wed", "Thu", "Fri", "Sat")
df |>
  mutate(week = fct_relevel(week, days)) |>
  ggplot(aes(x = week, y = tip)) +
  geom_bar(stat = "identity") +
  labs(title = "Tips by Weekday", x = "Weekday", y = "Tip ($)")
```

:::{.callout}
**Q: Why don’t we use `labels` in `factor()`?** Because the values (`"Mon"`, etc.) are already readable. You don’t need to change them, unless you want different names (e.g., `"Monday"`, etc.).

**Q: Why doesn’t `days` include all 7 days of the week?** We should include all possible levels when using `factor()`. But `fct_relevel()` behave differently and does not need it.
:::

<!--
Note the c() is the standard way of creating a vector 
but fct_relevel() accepts multiple strings directly via ..., so you can skip c() and write directly fct_relevel(week, "Mon", "Wed", "Thu", "Fri", "Sat"_
Both versions are valid

FOR CSS CLASS: add one example with fct_reorder() as it is the most straightforward application
-->

---

## Reflections

:::{.callout-tip}
- What happens when you don’t set the factor order?
- Which method among `factor()` or `fct_relevel()` do you prefer and why? Check the `forcats` package documentation for more functions, especially `fct_reorder()` which is straightforward to use
- Why was `stat = "identity"` necessary for this kind of plot?
:::

Want more practice? Download today's in-class materials for more practice exercises on working with factors!

---

## Recap: What We Learned Today

- What factors are and how to convert character or numeric vectors to factors  
- How to control the order of categories using `levels` and `labels`  
- How to fix common `geom_bar()` plotting issues (e.g., bar heights and order)

---

## To print these slides as pdf

Click on the icon bottom-left corner (the three lines) \> Tools \> PDF Export Mode \> Print as a Pdf
