---
title: "Lecture 9: Week 2 Review"
date: 2026-06-29
summary: "Week 2 Review and Q&A"
url_slides:
url_code:
page-layout: full
draft: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Info and Materials

* **Date**: {{< meta date >}}
* **Topics**: {{< meta summary >}}
* **Slides**: To be posted before class
* **Code**: To be posted before class

<!--
* **Slides**: [View Slides]({{< meta url_slides >}})
* **Code**: `usethis::use_course("{{< meta url_code >}}")`
-->

## Learning Objectives

Today, we will review key topics from Week 2. We will also make time to answer questions about Quiz 2 and Homework Assignment 2.

We will still have Poll Everywhere participation questions, along with time for additional questions. Depending on how much review is needed, we may finish a bit early. Any remaining time will be used for individual office hours.


## Before Class

- Bring any questions you have about the Week 2 materials!
- If you have not already done so, complete Lecture 8 participation questions. You can find them in the Lecture 8 Zoom chat (the recording is available on Canvas > UChicago Main Zoom > Cloud Recordings) or in [this document](https://docs.google.com/document/d/1f5jZ1ynOMV-axF-toNtec-KyOwhLvSYZCx0BlPaslxQ/edit?usp=sharing) after class. They will remain open until Friday morning (around 9 AM). Make sure to enter your name as you answer, so we can properly record your participation (do not answer a "guest").
- HW2 is open and due Thursday, July 2nd at 11:59 PM Chicago time. Access it from the [Assignments page](https://brinasab.github.io/css-website-summer/hw/) and submit it on Canvas. 
- Complete Quiz 2 from [Canvas](https://canvas.uchicago.edu/courses/72552). You have unlimited attempts. This is due 1-hour before today's class, no late submissions allowed.

