---
title: "Lecture 10: Importing Data with readr; Relational Data with dplyr"
date: 2026-06-30
summary: "Importing Data; Relational Data"
url_slides: 10-slides.qmd
url_code: css-materials/relational-data
page-layout: full
draft: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Info and Materials

* **Date**: {{< meta date >}}
* **Topics**: {{< meta summary >}}
* **Slides**: To be posted before class
* **Code**: To be posted before class

<!--
* **Slides**: [View Slides]({{< meta url_slides >}})
* **Code**: `usethis::use_course("{{< meta url_code >}}")`
-->


## Learning Objectives

- Importing and Exporting Data in R
- Managing Relational Data (e.g., linking and merging related tables)


## Before Class

- If you have not already done so, complete Lecture 9 participation questions. You can find them in the Lecture 9 Zoom chat (the recording is available on Canvas > UChicago Main Zoom > Cloud Recordings) or in [this document](https://docs.google.com/document/d/1f5jZ1ynOMV-axF-toNtec-KyOwhLvSYZCx0BlPaslxQ/edit?usp=sharing) after class. They will remain open until the start of this lecture (e.g., Lecture 10). Make sure to enter your name as you answer, so we can properly record your participation (do not answer a "guest").
- Check the readings below and come with questions!


## Readings

- Importing data: ["Chapter 7 Data import"](https://r4ds.hadley.nz/data-import.html) from "R for Data Science" 2nd Edition and [readr Documentation](https://readr.tidyverse.org/index.html)
- Relational data: ["Chapter 19 Joins"](https://r4ds.hadley.nz/joins) from "R for Data Science" 2nd Edition
