---
title: "Lecture 11: Tidydata with tidyr"
date: 2026-07-01
summary: "Tidydata with tidyr"
url_slides: 11-slides.qmd
url_code: css-materials/tidydata
page-layout: full
draft: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Info and Materials

* **Date**: {{< meta date >}}
* **Topics**: {{< meta summary >}}
* **Slides**: [View Slides]({{< meta url_slides >}})
* **Code**: `usethis::use_course("{{< meta url_code >}}")`

<!--
* **Slides**: To be posted before class
* **Code**: To be posted before class
-->


## Learning Objectives

* Define the concept of tidy data and its characteristics
* Practice tidying data using `tidyr`


## Before Class

- If you have not already done so, complete Lecture 10 participation questions. You can find them in the Lecture 10 Zoom chat (the recording is available on Canvas > UChicago Main Zoom > Cloud Recordings). You can also find them in [this document](https://docs.google.com/document/d/1f5jZ1ynOMV-axF-toNtec-KyOwhLvSYZCx0BlPaslxQ/edit?usp=sharing). They will remain open until the start of this lecture (e.g., Lecture 11). Make sure to enter your name as you answer, so we can properly record your participation (do not answer a "guest").
- Check the readings below and come with questions!


## Readings

* ["Chapter 5 Data tidying"](https://r4ds.hadley.nz/data-tidy) from "R for Data Science" 2nd Edition
* [tidyr Documentation](https://tidyr.tidyverse.org/)
* [tidyr Cheat Sheet](https://github.com/rstudio/cheatsheets/blob/main/tidyr.pdf)
