---
title: "Lecture 12: Strings and Regex with stringr; Dates with lubridate"
date: 2026-07-02
summary: "Strings and Regex with stringr; Dates with lubridate"
url_slides: 12-slides.qmd
url_code: css-materials/regular-expr
page-layout: full
draft: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Info and Materials

* **Date**: {{< meta date >}}
* **Topics**: {{< meta summary >}}
* **Slides**: [View Slides]({{< meta url_slides >}})
* **Code**: `usethis::use_course("{{< meta url_code >}}")`


## Learning Objectives

* Define Strings, Regular Expressions, and their uses
* Introduce `stringr`
* Practice using Regular Expressions in R to extract info from strings
* Introduce `lubridate` to manipulate dates in R (Update: moved to Monday, July 6)


## Before Class

- If you have not already done so, complete Lecture 11 participation questions. You can find them in the Lecture 11 Zoom chat (the recording is available on Canvas > UChicago Main Zoom > Cloud Recordings) or in [this document](https://docs.google.com/document/d/1f5jZ1ynOMV-axF-toNtec-KyOwhLvSYZCx0BlPaslxQ/edit?usp=sharing) after class. They will remain open until the start of this lecture (e.g., Lecture 12). Make sure to enter your name as you answer, so we can properly record your participation (do not answer a "guest").
- Check the readings below and come with questions!
- **Assignments coming up:**
  - Quiz 3 will open today right after this class, check [Canvas](https://canvas.uchicago.edu/courses/72552) and it's due Monday of Week 4 before class
  - Assignment 2 is due today (Thursday, July 2nd, 11:59 PM Chicago Time)
  - Assignments 3 and 5 (the optional one) will open tomorrow (Friday, July 3rd); check the Lecture page for their respective due dates
  - Check the [Oral Code Check page](oral-home.qmd) and sign-up by Sunday, July 5
  
  
## Readings

* [Chapter 14 "Strings"](https://r4ds.ha
dley.nz/strings) in "R for Data Science" 2nd Edition (especially 14.4 "Extracting data from strings")
* [Chapter 17](https://bookdown.org/rdpeng/rprogdatascience/regular-expressions.html#the-stringr-package) from *R Programming for Data Science*. Focus on the `stringr()` section — that’s all we cover in class, but the full chapter is a good reference if you want more
* [`stringr()` documentation and cheatsheet](https://stringr.tidyverse.org/)
* ["Chapter 17 Dates and times"](https://r4ds.hadley.nz/datetimes.html) from "R for Data Science" 2nd Edition
