---
title: "Lecture 13: Week 3 Review"
date: 2026-07-06
summary: "Week 3 Review and Q&A + Oral Code Checks Start"
url_slides: 
url_code:
page-layout: full
draft: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Info and Materials

* **Date**: {{< meta date >}}
* **Topics**: {{< meta summary >}}
* **Slides**: No slides for today
* **Code**: No in-class code for today

<!--
* **Slides**: [View Slides]({{< meta url_slides >}})
* **Code**: `usethis::use_course("{{< meta url_code >}}")`
-->

## Learning Objectives

Today, we will review key topics from Week 3. We will make time to answer questions about Quiz 3 and Homework Assignment 3, and we will still have Poll Everywhere participation questions. 

Today, we will also start the [online oral checks](oral-home.qmd), which will continue throughout weeks 4 and 5. 

Agenda (~15 minutes per item):

1. **Quiz 3 Review**
2. **Homework 3 Q&A**
3. **Finish Lecture 12 Content**: Manipulate dates with `lubridate`
4. **[Breakout activity: Week 3 review teams]()** [Link will be active on Monday]
5. **Class ends at 10:30 AM**


## Before Class

- Bring any questions you have about the Week 3 materials!
- If you have not already done so, complete Lecture 12 participation questions, by Friday morning (~9 AM) of Week 3. You can find them in the Lecture 12 Zoom chat (the recording is available on Canvas > UChicago Main Zoom > Cloud Recordings) or in [this document](https://docs.google.com/document/d/1f5jZ1ynOMV-axF-toNtec-KyOwhLvSYZCx0BlPaslxQ/edit?usp=sharing) after class. Make sure to enter your name as you answer, so we can properly record your participation (do not answer a "guest").
- **Assignments coming up:**
  - HW3 is posted on the [Assignments page](https://brinasab.github.io/css-website-summer/hw/)
  - Complete Quiz 3 from [Canvas](https://canvas.uchicago.edu/courses/72552). You have unlimited attempts. This is due 1-hour before today's class, no late submissions allowed.
