---
title: "Lecture 16: Control Flow with Loops"
date: 2026-07-09
summary: "Writing Loops"
url_slides: 16-slides.qmd
url_code: css-materials/loops
page-layout: full
draft: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Info and Materials

* **Date**: {{< meta date >}}
* **Topics**: {{< meta summary >}}
* **Slides**: [View Slides]({{< meta url_slides >}})
* **Code**: No in-class code to download

<!--
* **Slides**: To be posted before class
-->

## Learning Objectives

- Understand how for loops work
- Learn how to track and save results during a loop (e.g., running totals)
- Recognize the difference between looping over indexes and over elements
- Use for loop with if-else statements and within dataframes


## Before Class

- Review last lecture's materials, and complete the in-class code tutorials (downloadable from the lecture page; Lecture 15 tutorial titled `if-else-exercise.Rmd` will be particularly helpful for HW4)
- If you have not already done so, complete Lecture 15 participation questions. You can find them in the Zoom chat (the recording is available on Canvas > UChicago Main Zoom > Cloud Recordings) or in [this document](https://docs.google.com/document/d/1f5jZ1ynOMV-axF-toNtec-KyOwhLvSYZCx0BlPaslxQ/edit?usp=sharing) after class. They will remain open until the start of this lecture (e.g., Lecture 16). Make sure to enter your name as you answer, so we can properly record your participation (do not answer a "guest").


## Readings

- ["Chapter 27.5 For Loops"](https://r4ds.hadley.nz/base-R.html#for-loops) (high level intro here, slides unpack the details)
- ["Chapter 26 Iteration"](https://r4ds.hadley.nz/iteration) from "R for Data Science" 2nd Edition

