---
title: "Lecture 18: Control Flow with Loops (cont.); Functions"
date: 2026-07-14
summary: "Finish Loops; Introduce Functions"
url_slides: 18-slides.qmd
url_code: css-materials/functions
page-layout: full
draft: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Info and Materials

* **Date**: {{< meta date >}}
* **Topics**: {{< meta summary >}}
* **Slides**: To be posted before class
* **Code**: To be posted before class

<!--
* **Slides**: [View Slides]({{< meta url_slides >}})
* **Code**: `usethis::use_course("{{< meta url_code >}}")`
-->

<!-- `usethis::use_course("css-materials/functions")` -->

## Learning Objectives

**Loops (cont. from last lecture):**

- Review of using for loops within a data frame 
- Identify and apply alternatives to for loops in R, such as `map()`, `across()`, and `apply()`
- Introduce while loops

**Functions:**  

- Define functions and their purposes  
- Understand the difference between built-in and user-written functions  
- Learn the syntax of user-written functions  


## Before class

- Review [Lecture 16](https://brinasab.github.io/css-website-summer/lectures/16-home.html)
- If you have not already done so, complete Lecture 17 participation questions. You can find them in the Zoom chat (the recording is available on Canvas > UChicago Main Zoom > Cloud Recordings) or in [this document](https://docs.google.com/document/d/1f5jZ1ynOMV-axF-toNtec-KyOwhLvSYZCx0BlPaslxQ/edit?usp=sharing) after class. They will remain open until the start of this lecture (e.g., Lecture 18). Make sure to enter your name as you answer, so we can properly record your participation (do not answer a "guest").


## Readings

* Loops: See previous lecture
* Functions: [Chapter 15 "Functions"](https://r4ds.hadley.nz/functions) in "R for Data Science" 2nd Edition
