---
title: "Lecture 19: Functions (cont.)"
date: 2026-07-15
summary: "Functions (cont.)"
url_slides: 19-slides.qmd
#url_code: css-materials/functions
page-layout: full
draft: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Info and Materials

* **Date**: {{< meta date >}}
* **Topics**: {{< meta summary >}}
* **Slides**: [View Slides]({{< meta url_slides >}})
* **Code**: See the in-class code for Lecture 18 (Tuesday 7/14)


<!--
* **Slides**: To be posted before class
* **Code**: `usethis::use_course("{{< meta url_code >}}")`
-->

<!-- `usethis::use_course("css-materials/functions-bugs")` -->


## Learning Objectives

* Review and continue the lecture on Functions  
 

## Before class

- Review [Lecture 18](https://brinasab.github.io/css-website-summer/lectures/18-home.html), and especially the [last session of the slides on functions](https://brinasab.github.io/css-website-summer/lectures/18-slides.html#/introduction-to-functions) and come with questions. We will start class from that part!
- If you have not already done so, complete Lecture 18 participation questions. You can find them in the Zoom chat (the recording is available on Canvas > UChicago Main Zoom > Cloud Recordings) or in [this document](https://docs.google.com/document/d/1f5jZ1ynOMV-axF-toNtec-KyOwhLvSYZCx0BlPaslxQ/edit?usp=sharing) after class. They will remain open until the start of this lecture (e.g., Lecture 18). Make sure to enter your name as you answer, so we can properly record your participation (do not answer a "guest").


## Readings

* See the previous lecture for the readings on Functions

<!--
Optional readings on debugging:

* "Debugging R code" in [What They Forgot to Teach You About R](https://rstats.wtf/debugging-r)
* [21.6 Dealing with failure in *R for Data Science*](http://r4ds.had.co.nz/iteration.html#dealing-with-failure)
* [How to read an R help page](http://socviz.co/appendix.html#how-to-read-an-r-help-page)
-->