---
title: "Lecture 20: Reproducible Workflow"
date: 2026-07-16
summary: "Reproducible Workflow"
url_slides: 20-slides.qmd
url_code: css-materials/deep-dive-reproducible-git-rmd
page-layout: full
draft: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Info and Materials

* **Date**: {{< meta date >}}
* **Topics**: {{< meta summary >}}
* **Slides**: [View Slides]({{< meta url_slides >}})
* **Code**: `usethis::use_course("{{< meta url_code >}}")`

<!--
* **Slides**: To be posted before class
* **Code**: To be posted before class
-->
<!--`usethis::use_course("css-materials/deep-dive-reproducible-git-rmd")`-->

## Learning Objectives

* Define a project-oriented workflow in R and identify best R procedures
* Expand our current knowledge of R Markdown
* Learn the basics of Git/GitHub via terminal/command line 


## Before class

- Come with questions regarding the admin/logistic of the course or about the content we covered!
- If you have not already done so, complete Lecture 19 participation questions. You can find them in the Zoom chat (the recording is available on Canvas > UChicago Main Zoom > Cloud Recordings) or in [this document](https://docs.google.com/document/d/1f5jZ1ynOMV-axF-toNtec-KyOwhLvSYZCx0BlPaslxQ/edit?usp=sharing) after class. They will remain open until the start of this lecture (e.g., Lecture 20). Make sure to enter your name as you answer, so we can properly record your participation (do not answer a "guest").


## Readings

Not required, refer to them as you see fit:

* [Good Enough Practices in Scientific Computing](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005510)
* Chapters 1, 2, 3, 7 in [What They Forgot to Teach You About R](https://rstats.wtf/)
* Chapters 27 "R Markdown", 28 "Graphics for communication", and 29 "R Markdown formats" in [R for Data Science 1st Edition](http://r4ds.had.co.nz)
* Article on [Project-oriented workflow](https://www.tidyverse.org/articles/2017/12/workflow-vs-script/)
